<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VGSCH-ARM</AssemblyName>
    <RootNamespace>VgschArm</RootNamespace>
    <ApplicationIcon>vgsch.ico</ApplicationIcon>
    <Product>ARM Dezhurnogo VGSCH</Product>
    <Company>VGSCH</Company>
    <AssemblyTitle>ARM Dezhurnogo VGSCH</AssemblyTitle>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
  </ItemGroup>

  <ItemGroup Condition="Exists('vgsch.ico')">
    <None Update="vgsch.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
